apiVersion: v1
kind: Service
metadata:
  name: prism-backend
  namespace: controller
  labels:
    app: prism-backend
spec:
  selector:
    app: prism-backend
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP