name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./controller/pom.xml
          mvn clean package -f ./notification/pom.xml
          mvn clean package -f ./alertsubscription/pom.xml
          mvn clean package -f ./healthchecklog/pom.xml
          mvn clean package -f ./issue/pom.xml
          mvn clean package -f ./cctv/pom.xml
          mvn clean package -f ./network/pom.xml

      - name: Docker Build and push for Controller
        uses: docker/build-push-action@v4
        with:
          context: ./controller
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/controller:latest
            ghcr.io/${{ github.repository }}/controller:${{ github.ref_name }}
            
      - name: Docker Build and push for Notification
        uses: docker/build-push-action@v4
        with:
          context: ./notification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notification:latest
            ghcr.io/${{ github.repository }}/notification:${{ github.ref_name }}
            
      - name: Docker Build and push for Alertsubscription
        uses: docker/build-push-action@v4
        with:
          context: ./alertsubscription
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/alertsubscription:latest
            ghcr.io/${{ github.repository }}/alertsubscription:${{ github.ref_name }}
            
      - name: Docker Build and push for Healthchecklog
        uses: docker/build-push-action@v4
        with:
          context: ./healthchecklog
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/healthchecklog:latest
            ghcr.io/${{ github.repository }}/healthchecklog:${{ github.ref_name }}
            
      - name: Docker Build and push for Issue
        uses: docker/build-push-action@v4
        with:
          context: ./issue
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/issue:latest
            ghcr.io/${{ github.repository }}/issue:${{ github.ref_name }}
            
      - name: Docker Build and push for Cctv
        uses: docker/build-push-action@v4
        with:
          context: ./cctv
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cctv:latest
            ghcr.io/${{ github.repository }}/cctv:${{ github.ref_name }}
            
      - name: Docker Build and push for Network
        uses: docker/build-push-action@v4
        with:
          context: ./network
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/network:latest
            ghcr.io/${{ github.repository }}/network:${{ github.ref_name }}
            
