server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: controller
          uri: http://localhost:8082
          predicates:
            - Path=/cctvs/**, /users/**, 
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**, 
        - id: alertsubscription
          uri: http://localhost:8084
          predicates:
            - Path=/alertSubscriptions/**, 
        - id: healthchecklog
          uri: http://localhost:8085
          predicates:
            - Path=/healthCheckLogs/**, 
        - id: issue
          uri: http://localhost:8086
          predicates:
            - Path=/issues/**, 
        - id: cctv
          uri: http://localhost:8087
          predicates:
            - Path=/tvResolutions/**, 
        - id: network
          uri: http://localhost:8088
          predicates:
            - Path=/networkActions/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: controller
          uri: http://controller:8080
          predicates:
            - Path=/cctvs/**, /users/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: alertsubscription
          uri: http://alertsubscription:8080
          predicates:
            - Path=/alertSubscriptions/**, 
        - id: healthchecklog
          uri: http://healthchecklog:8080
          predicates:
            - Path=/healthCheckLogs/**, 
        - id: issue
          uri: http://issue:8080
          predicates:
            - Path=/issues/**, 
        - id: cctv
          uri: http://cctv:8080
          predicates:
            - Path=/tvResolutions/**, 
        - id: network
          uri: http://network:8080
          predicates:
            - Path=/networkActions/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
