apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecklog
  labels:
    app: healthchecklog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthchecklog
  template:
    metadata:
      labels:
        app: healthchecklog
    spec:
      containers:
        - name: healthchecklog
          image: "username/healthchecklog:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
