apiVersion: apps/v1
kind: Deployment
metadata:
  name: cctv
  labels:
    app: cctv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cctv
  template:
    metadata:
      labels:
        app: cctv
    spec:
      containers:
        - name: cctv
          image: "username/cctv:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
