apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsubscription
  labels:
    app: alertsubscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertsubscription
  template:
    metadata:
      labels:
        app: alertsubscription
    spec:
      containers:
        - name: alertsubscription
          image: "username/alertsubscription:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
